### ISSUE TITLE
About your code in final part

### ISSUE THREAD

**Issue by ChunchaoPeter** [aboustati/at_gp#1]
Hi Ayman,

Thanks for your sharing the code online. I am really like your code.
I am new to TensorFlow and GPflow. After reading your code, I am a bit confused about you final part of your code:

        Knn = self.kern.K(Xnew) if full_cov else self.kern.Kdiag(Xnew)
        f_mean, f_var = base_conditional(K_new, C, Knn, y, full_cov=full_cov, white=False)
        return f_mean + self.mean_function(Xnew), f_var

When I reading the paper: Adaptive Transfer Learning
http://www3.ntu.edu.sg/home/sinnopan/publications/[AAAI10]Adaptive%20Transfer%20Learning.pdf

the author may add some variance to the Knn in your code.  I just slightly change your code to add the variance:

        Knn = self.kern.K(Xnew) + tf.eye(tf.shape(Xnew)[0], dtype=settings.float_type)\
                   * self.likelihood.variance if full_cov else self.kern.Kdiag(Xnew)\
                                                               + self.source_likelihood.variance
        f_mean, f_var = base_conditional(K_new, C, Knn, y, full_cov=full_cov, white=False)
        return f_mean + self.mean_function(Xnew), f_var

I am not sure how the GPflow work in detail so I am not sure whether we need to add the variance in this way. Could you please clarify it?

Thanks in advance.

**Comment by aboustati** [comment]
Hi Chunchao,

Are you referring to eq (7) in the paper? This is the predictive distribution `p(y* | y_t, y_s) = \int p(y* | f*) p(f* | y_t, y_s) df*`. In the code, `build_predict` builds the tensor for `p(f* | y_t, y_s)` not the predictive distribution. You have to integrate the output with the likelihood to get the predictive distribution. You can do this by calling `predict_y`.

Let me know this is is helpful/answers you question.

Best wishes,

Ayman

**Comment by ChunchaoPeter** [comment]
Hi Ayman,


Great! Thanks for your help. :)
Yes, I am referring to the eq (7). I considered  build_predict  as predictive distribution previously. Thanks for your clarification.


Best wishes,
Chunchao
